services:
  - type: web
    runtime: "docker"
    name: n8n
    region: oregon # optional (defaults to oregon)
    plan: starter  # Other possible values: standard (defaults to starter)
    branch: main # optional (defaults to master)
    # dockerCommand: ./webdis.sh # optional (defaults to Dockerfile command)
    numInstances: 1
    healthCheckPath: /
    envVars:
      - key: PGHOST
        fromDatabase:
          name: n8nDB
          property: host
      - key: PGDATABASE
        fromDatabase:
          name: n8nDB
          property: database
      - key: PGPORT
        fromDatabase:
          name: n8nDB
          property: port
      - key: PGUSER
        fromDatabase:
          name: n8nDB
          property: user
      - key: PGPASSWORD
        fromDatabase:
          name: n8nDB
          property: password
      - key: N8N_RUNNERS_ENABLED
        value: "true"
      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: "true"
      - key: N8N_DIAGNOSTICS_ENABLED
        value: "false"
      - key: N8N_TEMPLATES_ENABLED
        value: "false"
      - key: EXTERNAL_FRONTEND_HOOKS_URLS
        value: ""
      - key: N8N_DIAGNOSTICS_CONFIG_FRONTEND
        value: ""
      - key: N8N_DIAGNOSTICS_CONFIG_BACKEND
        value: ""
      - key: N8N_HOST
        value: "n8n-e7oi.onrender.com"
      - key: N8N_PROTOCOL
        value: "https"
      - key: N8N_PORT
        value: "443"

    disk:
      name: n8nDisk
      mountPath: /home/node/.n8n
      sizeGB: 5

databases:
  - name: n8nDB
    plan: free
